[package]
name = "example"
type = "contract"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-package-v0.60.0", directory="noir-projects/aztec-nr/aztec" }
